"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require("../../middleware/auth");
const createEvent_1 = require("./createEvent");
const getEvents_1 = require("./getEvents");
const deleteEvent_1 = require("./deleteEvent");
const getEvent_1 = require("./getEvent");
const router = (0, express_1.Router)();
router.post("/", auth_1.authenticateToken, createEvent_1.createEventFunction);
router.get("/", auth_1.authenticateToken, getEvents_1.getEventsFunction);
router.delete("/:eventId", auth_1.authenticateToken, deleteEvent_1.deleteEventFunction);
router.get("/:eventId", auth_1.authenticateToken, getEvent_1.getEventFunction);
exports.default = router;
